version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: flask_container
    environment:
      - FLASK_APP=Server.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    env_file:
      - .env

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper_container
    depends_on:
      - web
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
